import { APP_CONFIG } from "../config/app";

export const STELLAR_NETWORK = APP_CONFIG.STELLAR_NETWORK;
export const HORIZON_URL = APP_CONFIG.HORIZON_URL;
export const NETWORK_PASSPHRASE = APP_CONFIG.NETWORK_PASSPHRASE;
export const RPC_URL = APP_CONFIG.RPC_URL;
